# Решение заданий к уроку 3

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$



### Решение

Теперь найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0$$

$(-1-\lambda)(6-\lambda)-2\cdot(-6) =0,$

$\lambda^2 - 6 \lambda + \lambda - 6 + 12 = 0$

$\lambda^2 - 5 \lambda + 6 = 0$

$(\lambda -2)(\lambda -3) = 0$

отсюда собственные значения:

$\lambda_1 = 2$

$\lambda_2 = 3$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

для 
$\lambda_1 = 2$

$\begin{cases}
-x_1-6x_2 = 2x_1 \\
2x_1+6x_2= 2x_2
\end{cases}$

$\begin{cases}
x_1 = -2 x_2 \\
x_1 = - 2x_2
\end{cases}$

Общее решение собственного вектора для $\lambda_1$:   $\,\,\, x_2 \cdot \begin{pmatrix}
-2\\ 
1
\end{pmatrix}$

для $\lambda_2 = 3$

$\begin{cases}
-x_1-6x_2 = 3x_1 \\
2x_1+6x_2= 3x_2
\end{cases}$

$\begin{cases}
x_1 = - \frac{3}{2} x_2 \\
x_1 = - \frac{3}{2}x_2
\end{cases}$

Общее решение собственного вектора для $\lambda_2$:   $\,\,\, x_2 \cdot \begin{pmatrix}
- \frac{3}{2}\\ 
1
\end{pmatrix}$



In [22]:
# проверим
import numpy as np
A = np.array([[-1, -6], [2, 6]])
w,v = np.linalg.eig(A)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [23]:
# если x2 = 0.4472136 для первого собственного значения = 2, то x1 должен быть 
v[1,0]*(-2)
# что соответствует 

-0.8944271909999159

-----

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.



### Решение

$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix} = -1\cdot \begin{pmatrix}
1 & 0\\ 
0 & 1
\end{pmatrix} = - E$

возьмем произвольный вектор $\begin{pmatrix}
a\\ 
b
\end{pmatrix}$ и проверим 

$A \cdot \begin{pmatrix}
a\\ 
b
\end{pmatrix} = \lambda \cdot \begin{pmatrix}
a\\ 
b
\end{pmatrix}$

$- E \cdot \begin{pmatrix}
a\\ 
b
\end{pmatrix} = - \begin{pmatrix}
a\\ 
b
\end{pmatrix} = \lambda \begin{pmatrix}
a\\ 
b
\end{pmatrix} \,\,\, \to  \,\,\, \lambda = -1$

Следовательно для собственного значения $\lambda = -1$ __любой__ вектор является для него собственным.

------

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



### Решение 

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Из этого будет следовать, что 

$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1 +3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda= 2
\end{cases}$$


Следовательно вектор $x=(1,1)$ является собственным вектором этого линейного оператора при $\lambda = 2$

In [50]:
# Проверим
B = np.array([[1,1],[-1,3]])
w1,v1 = np.linalg.eig(B)
print(f'Собственные значения:\n{w1}')
print(f'Собственные векторы:\n{v1}')


Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


------

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

### Решение

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix} \begin{pmatrix}
3 \\ 
-3 \\
-4 
\end{pmatrix}  = \lambda \begin{pmatrix}
3 \\ 
-3 \\
-4 
\end{pmatrix} $

$\begin{cases}
-9 =3 \cdot\lambda \\ 
9 = -3 \cdot \lambda \\
-12 = -4 \cdot \lambda
\end{cases} \Rightarrow
\begin{cases}
\lambda= -3\\ 
\lambda= -3\\
\lambda = 3
\end{cases}$

Cледовательно, вектор $x=(3,-3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$

In [26]:
# Проверим
C = np.array([[0, 3,0],[3,0,0], [0, 0, 3]])
w2,v2 = np.linalg.eig(C)
print(f'Собственные значения:\n{w2}')
print(f'Собственные векторы:\n{v2}')

Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
